# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: main

# The type of the application to build.
type: php:7.4
build:
    flavor: none

hooks:
    build: |
        curl -sS https://platform.sh/cli/installer | php

relationships:
    elasticsearch65: 'elasticsearch65:elasticsearch'
    elasticsearch68: 'elasticsearch68:elasticsearch'
    elasticsearch72: 'elasticsearch72:elasticsearch'
    elasticsearch75: 'elasticsearch75:elasticsearch'
    elasticsearch79: 'elasticsearch79:elasticsearch'
    elasticsearch710: 'elasticsearch710:elasticsearch'

# The size of the persistent disk of the application (in MB).
disk: 128

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            root: 'web'
            index: ['index.html']
        "/relationships":
            # The public directory of the app, relative to its root.
            root: "relationships/web"
            # The front-controller script to send non-static requests to.
            passthru: "/relationships/index.php"

crons:
    renewcert:
        # Force a redeploy at 10 am (UTC) on the 1st and 15th of every month.
        spec: '0 10 1,15 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi

# mounts:
#     networkstorage:
#         source: service
#         service: networkstorage
#         source_path: networkstorage
