name: java
type: "java:8"

disk: 1024

hooks:
  build: mvn clean install -U

relationships:
  database: 'mariadb104:mysql'
  postgresql: 'postgresql12:postgresql'
  mongodb: 'mongodb36:mongodb'
  redis: 'redis6:redis'
  elasticsearch: 'elasticsearch77:elasticsearch'
  memcached: 'memcached16:memcached'
  solr: 'solr86:solr'
  rabbitmq: 'rabbitmq39:rabbitmq'
  influxdb: 'influxdb18:influxdb'
  kafka: 'kafka25:kafka'

web:
  commands:
    start:  java -jar target/java-language-example.jar --server.port=$PORT
