//go:generate go run generators/include-source.go

package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	Config "github.com/platformsh/language-examples/conf"
	"github.com/platformsh/language-examples/examples"
	"html/template"
	"log"
	"net/http"
)

type exampleDef struct {
	callback func() string
	source   string
	name     string
	output   string
}

// This is a map of struct pointers so that we can update it inline later in main().
type exampleList map[string]*exampleDef

const pageTemplate = `<html>
<head>
    <title>Platform.sh PHP service examples</title>
    <style type="text/css">
        details {
            margin-top: 1em;
            border: 1px solid #aaa;
            border-radius: 4px;
            padding: 0.5em;
            width: 90%;
        }

        summary {
            font-weight: bold;
            margin: -.5em -.5em 0;
            padding: .5em;
        }

        details[open] {
            padding: .5em;
        }

        details[open] summary {
            border-bottom: 1px solid #aaa;
            margin-bottom: .5em;
        }

        table, table td, table th {
            border: 1px solid black;
        }
    </style>
</head>
<body>

<h1>Service examples for Go</h1>

{{ range $def := .defList }}
<details>
	<summary>{{.name}} Sample Code</summary>
	<section>
	<h3>Source</h3>
	{{.source}}
	</section>
	<section>
	<h3>Output</h3>
	{{.output}}
	</section>
</details>
{{ end }}

</body>
</html>
`

func exampleDefinitions() exampleList {
	ex := exampleList{}

	// The source constants are generated by `go generate` in the sources.go file.
	ex["mysql"] = &exampleDef{name: "MySQL", callback: examples.MySQL, source: Mysql}
	//ex["postgresql"] = exampleDef{name: "PostgreSQL", callback: examples.Postgresql, source: Postgresql}

	return ex
}

func debug(v interface{}) {
	fmt.Printf("%+v\n", v)
}

func main() {
	r := gin.Default()

	ex := exampleDefinitions()

	// Precompute the output for each service, since it's not going to change.
	for idx, _ := range ex {
		ex[idx].output = ex[idx].callback()
	}

	// Compile the page template once, ahead of time.
	pageTpl, err := template.New("service").Parse(pageTemplate)
	if err != nil {
		log.Fatal("Error parsing page template", err)
	}

	r.GET("/:service", func(c *gin.Context) {
		service := c.Param("service")
		c.String(http.StatusOK, ex[service].source)
	})

	r.GET("/:service/output", func(c *gin.Context) {
		service := c.Param("service")
		c.String(http.StatusOK, ex[service].output)
	})

	r.GET("/", func(c *gin.Context) {
		c.Status(http.StatusOK)
		c.Header("Content-Type", "text/html")

		page := struct {
			defList exampleList
		}{defList: ex}

		_ = pageTpl.Execute(c.Writer, page)
	})

	// Listen and Server in the port defined by Platform.sh.
	err = r.Run(":" + Config.PshConfig.Port())
	if err != nil {
		log.Fatal(err)
	}
}
