# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: python

# The runtime the application uses.
type: "python:3.8"

# The build-time dependencies of the app.
dependencies:
    python3:
       pipenv: "2018.10.13"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      pipenv install --system --deploy

# The size of the persistent disk of the application (in MB).
disk: 1024
# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'mariadb104:mysql'
    postgresql: 'postgresql12:postgresql'
    solr: 'solr86:solr'
    redis: 'redis6:redis'
    elasticsearch: 'elasticsearch77:elasticsearch'
    mongodb: 'mongodb36:mongodb'
    rabbitmq: 'rabbitmq39:rabbitmq'
    influxdb: 'influxdb18:influxdb'
    memcached: 'memcached16:memcached'
    kafka: 'kafka25:kafka'

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: python web/index.py

    locations:
        "/python":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: true
