name: nodejs
type: nodejs:14

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: 'mariadb104:mysql'
  postgresql: 'postgresql12:postgresql'
  solr: 'solr86:solr'
  redis: 'redis6:redis'
  elasticsearch: 'elasticsearch77:elasticsearch'
  mongodb: 'mongodb36:mongodb'
  opensearch: 'opensearch12:opensearch'
  rabbitmq: 'rabbitmq39:rabbitmq'
  influxdb: 'influxdb18:influxdb'
  memcached: 'memcached16:memcached'
  vault-kms: 'vault-kms:sign'

web:
  commands:
    start: "node index.js"
    #in this setup you will find your application stdout and stderr in /app/run/logs
  locations:
    "/public":
      passthru: false
      root: "public"
      # Whether to allow files not matching a rule or not.
      allow: true
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true

mounts:
  "run":
    source: local
    source_path: 'run'

disk: 512
