name: nodejs
type: nodejs:14

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: 'mysql:mysql'
  postgresql: 'postgresql:postgresql'
  solr: 'solr:solr'
  redis: 'redis:redis'
  elasticsearch: 'elasticsearch:elasticsearch'
  mongodb: 'mongodb:mongodb'
  rabbitmq: 'rabbitmq:rabbitmq'
  influxdb: 'influxdb:influxdb'
  memcached: 'memcached:memcached'

web:
  commands:
    start: "nodejs index.js"
    #in this setup you will find your application stdout and stderr in /app/run/logs
  locations:
    "/public":
      passthru: false
      root: "public"
      # Whether to allow files not matching a rule or not.
      allow: true
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true

mounts:
  "/run": "shared:files/run"

disk: 512
